dist: trusty
sudo: false
language: php

php:
  - 7.0

env:
  - WP_VERSION=latest DEV_LIB_PATH=node_modules/wp-dev-lib WP_ORG_SLUG=code-prettify

install:
  - nvm install node
  - npm install
  - find "$(npm bin)" -print
  - source $DEV_LIB_PATH/travis.install.sh

script:
  - source $DEV_LIB_PATH/travis.script.sh

after_script:
  - source $DEV_LIB_PATH/travis.after_script.sh

deploy:
  provider: script
  script: npm run deploy trunk
  on:
    php: 7.0
    branch: master
